version: "3.8"
services:
  postgresdb:
    image: postgres:14.4-alpine
    environment:
      - POSTGRES_HOST=${POSTGRESQL_HOST}
      - POSTGRES_USER=${POSTGRESQL_USER}
      - POSTGRES_PASSWORD=${POSTGRESQL_PASSWORD}
      - POSTGRES_DB=${POSTGRESQL_DATABASE}
    volumes:
      - postgresAPI:/var/lib/postgresql/data
    ports:
      - 5432:5432
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRESQL_USER} -d ${POSTGRESQL_DATABASE}"]
      interval: 5s
      timeout: 5s
      retries: 5
  api:
    build:
      context: ./
      dockerfile: Dockerfile
    environment:
      - POSTGRESQL_HOST=${POSTGRESQL_HOST}
      - POSTGRESQL_USER=${POSTGRESQL_USER}
      - POSTGRESQL_PASSWORD=${POSTGRESQL_PASSWORD}
      - POSTGRESQL_DATABASE=${POSTGRESQL_DATABASE}
      - HTTP_PORT=${HTTP_PORT}
      - CAT_API_URL=${CAT_API_URL}
      - LOG_LEVEL=${LOG_LEVEL}
    depends_on:
      postgresdb:
        condition: service_healthy
    ports:
      - 8080:8080
volumes:
  api:
  postgresAPI:
    driver: local
